name: Testing Docker With Tests

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Only
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          target: test
          tags: idjohnson/dockerwithtests:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
